# russian_roulette - 麦麦轮盘游戏插件配置文件
# 在命运的舞台上，勇士们围坐一圈，手中紧握那把只装有一颗子弹的左轮手枪

# 插件基本配置
[plugin]

# 插件配置文件版本号
config_version = "1.1.0"

# 是否启用插件
enabled = true


# 游戏常量配置
[game_constants]

# 最大等待时间（秒）
max_wait_time = 120

# 最大参与人数
max_participants = 6

# 最小禁言时间（秒）
min_mute_time = 60

# 最大禁言时间（秒）
max_mute_time = 3600


# 对话配置
[dialogue]

# 游戏启动消息
start_message = "哈哈，捡到一把俄罗斯左轮手枪啦，有没有胆肥的勇士，请说麦麦开枪来开始游戏，中枪的就要禁言哦"

# 空子弹随机对话列表 (5条不重复台词)
empty_bullet_messages = [
    "嘿嘿，我要开枪咯，左轮手枪指着{user_name}，扣动扳机，咔咔，没有打中，你真好彩哎",
    "哦豁，又一个不怕死的，左轮手枪指着{user_name}，扣动扳机，咔咔，没有打中，嘿嘿，你有没有吓破胆",
    "我麦麦神枪手可从来没有失过手，左轮手枪指着{user_name}，猛烈扣下扳机，咔咔，没有打中，命真大啊",
    "想尿裤子就尽情的尿吧，左轮手枪猛的指着{user_name}，咔咔，没有打中",
    "我想吃牛肉面了，但你的牛肉面有葱花，左轮手枪迅速指着{user_name}的头，扣动扳机，咔咔，没有打中，哎呀其实有葱花的更香"
]

# 中弹消息
hit_message = "我看你乌云盖顶呢，你确定要玩这游戏，左轮手枪迅速指着{user_name}扣动扳机，砰！鲜血染红了墙壁！"


# 日志记录配置
[logging]

# 日志级别
level = "INFO"

# 日志前缀
prefix = "[russian_roulette]"